kind: pipeline
name: default

steps:
  - name: semantic-release
    image: cenk1cenk2/semantic-release-drone
    settings:
      mode: predict # "release" means the actual release and "predict" means to generate the version in dry run to use it e.g. before build
      git_method: gh # set for git authentication with gh (Github), gl (GitLab), bb (BitBucket), cr (Credentials)
      git_user_name:
        from_secret: GIT_USERNAME
      git_user_email:
        from_secret: GIT_EMAIL
      github_token:
        from_secret: github_token
      npm_token:
        from_secret: npm_token

  # - name: publish
  #   image: node:current-alpine
  #   commands:
  #     - yarn global add npm-cli-login standard-version
  #     - npm-cli-login -u $NPM_USERNAME -p $NPM_PASSWORD -e $NPM_EMAIL
  #     - npm publish --access public
  #     - npm logout
  #   trigger:
  #     branch:
  #       - master
  #     event:
  #       - push