kind: pipeline
name: default

steps:
  - name: semantic-release
    image: cenk1cenk2/semantic-release-drone
    settings:
      mode: release
      git_method: gh
      git_user_name:
        from_secret: GIT_USERNAME
      git_user_email:
        from_secret: GIT_EMAIL
      github_token:
        from_secret: GITHUB_TOKEN
      npm_token:
        from_secret: NPM_TOKEN