kind: pipeline
name: default

trigger:
  event:
    - tag

steps:
  - name: publish
    image: node:current-alpine
    commands:
      - yarn global add npm-cli-login
      - npm-cli-login -u $NPM_USERNAME -p $NPM_PASSWORD -e $NPM_EMAIL
      - npm publish --access public
      - npm logout
    environment:
      NPM_USERNAME:
        from_secret: NPM_USERNAME
      NPM_PASSWORD:
        from_secret: NPM_PASSWORD
      NPM_EMAIL:
        from_secret: NPM_EMAIL