kind: pipeline
name: default

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: semantic-release
    image: cenk1cenk2/drone-semantic-release
    settings:
      mode: release
      update_readme: true
      git_method: gh
      git_user_name:
        from_secret: GITHUB_USERNAME
      git_user_email:
        from_secret: GITHUB_EMAIL
      github_token:
        from_secret: GITHUB_TOKEN
      npm_token:
        from_secret: NPM_TOKEN
    when:
      branch:
        - master
      event:
        - push
        
image_pull_secrets:
  - dockerconfigjson
