---
stages:
  - publish

include:
  - project: devops/pipelines
    ref: semantic-release@2.0.0
    file:
      - /semantic-release/publish.gitlab-ci.yml

semantic-release:
  stage: publish
  extends: .semantic-release
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^(master|main|alpha|beta|rc|next)$/'
      interruptible: true
    - when: never